"""Providers exposed by rules_riviera."""

RivieraToolInfo = provider(
    doc = "One Riviera executable, with everything needed to actually run it.\n\n" +
          "A bare `File` is not enough: an executable bound to a\n" +
          "`sh_binary` / `py_binary` wrapper (the usual way to point at a\n" +
          "site install, source a license env file, or shell into a\n" +
          "container) carries `data` deps in its runfiles, and those are\n" +
          "dropped if only the executable File reaches the action.\n\n" +
          "Two fields, one per consumer shape: pass `files_to_run` to\n" +
          "`ctx.actions.run(tools = ...)`, or merge `runfiles` into an\n" +
          "executable / test rule's runfiles. Both stage the executable\n" +
          "itself, so neither needs pairing with a separate File. Read\n" +
          "`files_to_run.executable` when all you need is a path or an\n" +
          "rlocation key.",
    fields = {
        "files_to_run": "FilesToRunProvider; pass in `ctx.actions.run(tools = [...])` so the tool's own runfiles are staged alongside it. `.executable` is the tool File.",
        "runfiles": "runfiles; the executable plus its default runfiles, for merging into an executable/test rule's runfiles.",
    },
)

RivieraToolchainInfo = provider(
    doc = "An Aldec Riviera-PRO toolchain — one `RivieraToolInfo` per Riviera executable.\n\n" +
          "`vsimsa` is the only load-bearing tool: it is the one binary the\n" +
          "rules invoke across the Bazel action boundary, both from\n" +
          "`riviera_library`'s compile action and from `riviera_sim_test`\n" +
          "at test time. Its toolchain attr is mandatory.\n\n" +
          "Every other tool runs inside vsimsa's TCL interpreter and never\n" +
          "crosses the boundary — including `acdb`, whose coverage reports\n" +
          "are generated by an `acdb report` TCL command in the same vsimsa\n" +
          "invocation as the simulation. They default to a PATH-resolving\n" +
          "shim and are exposed here so consumers can bind / override them\n" +
          "if a rule of their own needs a Bazel-visible path.",
    fields = {
        "acdb": "RivieraToolInfo; the `acdb` coverage-database tool. Optional — coverage reporting runs as an `acdb report` TCL command inside vsimsa, not through this attr.",
        "acom": "RivieraToolInfo; the `acom` VHDL compiler.",
        "alib": "RivieraToolInfo; the `alib` library-creation tool.",
        "alog": "RivieraToolInfo; the `alog` Verilog/SystemVerilog compiler.",
        "asim": "RivieraToolInfo; the `asim` elaborator + simulator.",
        "env": "dict[str, str]; extra environment variables for actions.",
        "jobs": "int; default CPU-count hint for Riviera actions/tests. `-1` = no hint (Bazel decides); `0` = explicit no hint; `N > 0` = request N CPUs. Rule-level `jobs = -1` inherits this value.",
        "requires_network": "bool; whether Riviera actions need network access (e.g. FlexLM license server).",
        "riviera": "RivieraToolInfo; the interactive Riviera-PRO IDE. No rule in this repo invokes it; bound so a consumer-authored rule can reach the wave viewer / TCL console.",
        "version": "string; toolchain version identifier for diagnostics.",
        "vmap": "RivieraToolInfo; the `vmap` library-mapping tool.",
        "vsim": "RivieraToolInfo; the `vsim` interactive driver.",
        "vsimsa": "RivieraToolInfo; the `vsimsa` batch-mode driver — invoked by every riviera_library compile action and by riviera_sim_test at test time. Mandatory on the toolchain rule.",
    },
)

RivieraLibraryInfo = provider(
    doc = "A self-contained Aldec Riviera library.\n\n" +
          "`riviera_library` always compiles the full transitive HDL graph\n" +
          "into ONE library, so consumers only ever need to `vmap` this one\n" +
          "directory — there's no transitive-library plumbing on the wire.",
    fields = {
        "language": "string; one of 'verilog', 'vhdl', 'mixed'.",
        "library_dir": "File; TreeArtifact holding the compiled library.",
        "name": "string; logical Riviera library name used in `vmap`.",
    },
)
